---
# file: roles/corosync/tasks/auth.yml
- name: Create /etc/corosync/
  file:
    path: /etc/corosync
    owner: root
    group: root
    mode: 0755
    state: directory

- name: "Copy {{ corosync_authkey }}"
  copy:
    src="{{ corosync_authkey }}"
    dest=/etc/corosync/authkey
    mode=0400
  notify: restart corosync
