---
# file: roles/corosync/tasks/install.yml
- name: Installing Corosync package
  package:
    name=corosync
    state=present
  when:
  - ansible_distribution_release != 'jessie' or corosync_debian_backports is not defined or not (corosync_debian_backports | bool)


- name: Enabling Corosync service
  service:
    name=corosync
    enabled=yes
